/**
 * Single bulletin board post output model returned from backend REST endpoints.
 */
export interface PostResponse {
  /** Unique auto-incremented database identifier. */
  readonly id: number;
  /** Contributor display name. */
  readonly name: string;
  /** Optional public contributor email address, or null if not provided. */
  readonly email: string | null;
  /** Message subject or title. */
  readonly title: string;
  /** Message body content. */
  readonly message: string;
  /** Submission timestamp in ISO 8601 UTC format. */
  readonly created_at: string;
}

/**
 * Paginated collection payload representing a page of bulletin board posts.
 * Guaranteed to provide an empty array for items on zero-result queries.
 */
export interface PagedPostResponse {
  /** Array of post records on current page (guaranteed non-null, [] on zero results). */
  readonly items: readonly PostResponse[];
  /** Zero-based current page index. */
  readonly page: number;
  /** Page size limit. */
  readonly size: number;
  /** Total number of posts matching query. */
  readonly total_items: number;
  /** Total number of pages available. */
  readonly total_pages: number;
}

/**
 * Input request payload for submitting a new post to the bulletin board.
 */
export interface CreatePostRequest {
  /** Contributor display name (1–50 characters, non-blank). */
  name: string;
  /** Optional public email address (max 254 characters, valid format). */
  email?: string | null;
  /** Message title (1–100 characters, non-blank). */
  title: string;
  /** Message body content (1–4,000 characters, non-blank). */
  message: string;
}

/**
 * Detailed description of an invalid request parameter conforming to RFC 9457 extensions.
 */
export interface InvalidParam {
  /** The field or parameter name violating validation constraints. */
  readonly name: string;
  /** Human-readable violation explanation. */
  readonly reason: string;
}

/**
 * Standard RFC 9457 Problem Details for HTTP APIs error response.
 */
export interface ProblemDetails {
  /** A URI reference identifying the problem type. */
  readonly type: string;
  /** A short human-readable summary of the problem type. */
  readonly title: string;
  /** The HTTP status code generated by origin server. */
  readonly status: number;
  /** A human-readable explanation specific to this problem occurrence. */
  readonly detail: string;
  /** A URI reference identifying the specific occurrence of the problem. */
  readonly instance: string;
  /** Optional list of invalid parameters for validation failures. */
  readonly invalid_params?: readonly InvalidParam[];
}
