package com.example.bulletinboard.exception;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.micronaut.serde.annotation.Serdeable;

import java.util.List;

/**
 * Standard RFC 9457 Problem Details for HTTP APIs payload.
 *
 * @param type          a URI reference that identifies the problem type
 * @param title         a short, human-readable summary of the problem type
 * @param status        the HTTP status code generated by the origin server
 * @param detail        a human-readable explanation specific to this occurrence of the problem
 * @param instance      a URI reference that identifies the specific occurrence of the problem
 * @param invalidParams optional list of invalid parameters for validation failures
 */
@Serdeable
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ProblemDetails(
        String type,
        String title,
        int status,
        String detail,
        String instance,
        @JsonProperty("invalid_params")
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        List<InvalidParam> invalidParams
) {
    /**
     * Compact constructor guaranteeing immutability of invalid parameters list.
     */
    public ProblemDetails {
        invalidParams = (invalidParams == null) ? null : List.copyOf(invalidParams);
    }
}
